dart_code_metrics:
  extends:
    - recommended
    - package:dart_code_metrics_presets/all.yaml
  rules:
    - avoid-late-keyword: false
    - member-ordering: false
    - prefer-match-file-name: false
    - no-magic-number: false


linter:
  rules:
    unnecessary_constructor_name: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_constructors_over_static_methods: true