targets:
  $default:
    sources:
      - $package$
      - lib/**
      - pubspec.yaml
    builders:
      pubspec_generator:
        options:
          output: lib/src/common/constants/pubspec.yaml.g.dart
      flutter_gen:
        options: 
          output: lib/generated/ # Optional (default: lib/gen/)
          line_length: 80