name: book_talk
description: "BookTalk: an app for booking meeting rooms in the office."
publish_to: "none"
version: 0.0.1+1

# repository: https://github.com/NM4ik/book_talk
environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.8 <4.0.0"

workspace:
  - packages/book_talk_ui
  - packages/rest_client

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # State and data flow
  rxdart: ^0.28.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0

  # Router
  octopus: ^0.0.9

  # Device local data
  shared_preferences: ^2.5.3

  # UI
  book_talk_ui:
    path: packages/book_talk_ui
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  animations: ^2.0.11

  # Network
  dio: ^5.9.0
  rest_client:
    path: packages/rest_client

  # Utils
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  collection: ^1.19.1
  image_picker: ^1.1.2
  dart_jsonwebtoken: ^3.2.0
  talker_flutter: ^4.9.3
  flutter_dotenv: ^5.2.1
  meta: ^1.16.0
  clock: 1.1.2

dev_dependencies:
  flutter_gen: ^5.11.0
  flutter_gen_runner: ^5.11.0
  pubspec_generator: ^4.3.0
  build_runner: ^2.4.13
  dartdoc: ^8.3.4
  melos: ^6.3.3
  
  # Analysis
  lint_rules:
    git:
      url: https://github.com/NM4ik/handbook
      path: lint_rules

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - lib/l10n/
    - assets/images/
  shaders:
    - assets/shaders/shimmer.frag
    
# flutter_intl:
#   enabled: true
