name: book_talk

description: "BookTalk: an app for booking meeting rooms in the office."

publish_to: "none"

version: 0.0.1+1

#repository: https://github.com/NM4ik/book_talk

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter

  # Stream
  rxdart: ^0.28.0
  flutter_bloc: ^8.1.6

  # Logger
  l: ^4.0.2

  # Router
  octopus: ^0.0.9
  bloc_concurrency: ^0.2.5

  # Device local data
  shared_preferences: ^2.3.2

  # UI lib
  book_talk_ui:
    path: packages/ui/book_talk_ui

  # UI
  cached_network_image: ^3.4.1

  # Utils
  uuid: ^4.5.1

dev_dependencies:
  pubspec_generator: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
