name: book_talk

description: "BookTalk: an app for booking meeting rooms in the office."

publish_to: "none"

version: 0.0.1+1

#repository: https://github.com/NM4ik/book_talk

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter

  # Stream
  rxdart: ^0.28.0
  flutter_bloc: ^8.1.6

  # Logger
  l: ^4.0.2

  # Router
  octopus: ^0.0.9
  bloc_concurrency: ^0.2.5

  # Device local data
  shared_preferences: ^2.3.2

  # UI lib
  book_talk_ui:
    path: packages/ui/book_talk_ui

  # UI
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3

  # Utils
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  collection: ^1.18.0

dev_dependencies:
  pubspec_generator: ^4.0.0
  build_runner: ^2.4.13
  dart_code_metrics_presets: ^2.17.0
  dartdoc: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  shaders:
    - assets/shaders/shimmer.frag
