name: book_talk

description: "BookTalk: an app for booking meeting rooms in the office."

publish_to: "none"

version: 0.0.1+1

#repository: https://github.com/NM4ik/book_talk

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.6.8
  pedant: ^1.1.0

flutter:
  uses-material-design: true
