name: rest_client
description: "Rest client for BookTalk app"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.8 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4