name: book_talk_ui
description: "UI-Package for BookTalk app"
version: 0.0.1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.8 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: lib/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/fonts/Poppins/Poppins-Light.ttf
          weight: 300
          